#!/bin/bash
NAME=$1
set -e

docker exec -it $NAME"_web_1" python3 -m ptvsd --host localhost --port 5678 /usr/bin/odoo --http-port 8070 --db_host db --db_port 5432 --db_user odoo --db_password odoo ${@:2} ||
docker exec -it $NAME"_web_1" python3 -m ptvsd --host localhost --port 5678 /usr/bin/odoo --xmlrpc-port 8070 --db_host db --db_port 5432 --db_user odoo --db_password odoo ${@:2}
