#!/bin/bash
SCRIPT=`realpath $0`;
SCRIPTPATH=`dirname $SCRIPT`;
if [ $# != 2 ]; then
    echo "USAGE: $0 NAME VERSION";
    exit 1;
fi
NAME=$1;
VERSION=$2;
# TODO REPO_URL=$3
set -e
if [ -d $HOME/dockers/$NAME ]; then
    echo "Project '$NAME' already exists";
    exit 1;
fi
cp -r $SCRIPTPATH/templates/$VERSION $HOME/dockers/$NAME;
$SCRIPTPATH/odoo-up $NAME;
