#!/bin/bash
NAME=$1
set -e
cd "$(dirname "$0")"
if [ ! -d /dockers/$NAME ]; then
    echo "Project '$NAME' does not exists"
    exit 1
fi
read -p "Are you sure? [y/n]"
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ./odoo_down $NAME
    docker volume rm $NAME"_web-data"
    docker volume rm $NAME"_db-data"
    rm -rf /dockers/$NAME
fi
