#!/bin/bash
SCRIPT=`realpath $0`;
SCRIPTPATH=`dirname $SCRIPT`;
NAME=$1;
set -e;
cd $SCRIPTPATH;
if [ ! -d $HOME/dockers/$NAME ]; then
    echo "Project '$NAME' does not exists";
    exit 1;
fi
read -p "Are you sure? [y/n]";
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ./odoo-down $NAME;
    docker volume rm $NAME"_web-data";
    docker volume rm $NAME"_db-data";
    rm -rf $HOME/dockers/$NAME;
fi
